#define LAMP_SHOOT_AGAIN          0
#define LAMP_BALL_SAVER_KICKER    1
#define LAMP_CENTER_FIRE          2
#define LAMP_CENTER_POWER         3
#define LAMP_TOP_F                4
#define LAMP_TOP_I                5
#define LAMP_TOP_R                6
#define LAMP_TOP_E                7
#define LAMP_POWER_1              8
#define LAMP_POWER_2              9
#define LAMP_POWER_3              10
#define LAMP_RIGHT_INLANE         11
#define LAMP_LEFT_INLANE          12
#define LAMP_BONUS_1              13
#define LAMP_BONUS_2              14
#define LAMP_BONUS_3              15
#define LAMP_BONUS_4              16
#define LAMP_BONUS_5              17
#define LAMP_BONUS_6              18
#define LAMP_BONUS_7              19
#define LAMP_BONUS_8              20
#define LAMP_BONUS_9              21
// 22 is not used
#define LAMP_BONUS_10             23
#define LAMP_BONUS_20             24
#define LAMP_1_STANDUP            25
#define LAMP_2_STANDUP            26
#define LAMP_3_STANDUP            27
#define LAMP_4_STANDUP            28
#define LAMP_5_STANDUP            29
#define LAMP_6_STANDUP            30
#define LAMP_SPINNER              31
#define LAMP_LEFT_SAUCER          32
#define LAMP_RIGHT_SAUCER         33
#define LAMP_TOP_SAUCER           34
#define LAMP_BONUS_2X             35
#define LAMP_BONUS_3X             36
#define LAMP_BONUS_4X             37
#define LAMP_BONUS_5X             38
#define LAMP_EXTRA_BALL           39
#define LAMP_10K_FIREPOWER        40
#define LAMP_30K_FIREPOWER        41
#define LAMP_50K_FIREPOWER        42
#define LAMP_TOP_LEFT_POP         43
#define LAMP_TOP_RIGHT_POP        44
#define LAMP_BOTTOM_RIGHT_POP     45
#define LAMP_BOTTOM_LEFT_POP      46
#define LAMP_LEFT_OUTLANE         47
#define LAMP_RIGHT_OUTLANE        48
#define LAMP_HEAD_1_PLAYER        49
#define LAMP_HEAD_2_PLAYER        50
#define LAMP_HEAD_3_PLAYER        51
#define LAMP_HEAD_4_PLAYER        52
#define LAMP_HEAD_MATCH           53
#define LAMP_HEAD_BALL_IN_PLAY    54
#define LAMP_APRON_CREDITS        55
#define LAMP_HEAD_PLAYER_1_UP     56
#define LAMP_HEAD_PLAYER_2_UP     57
#define LAMP_HEAD_PLAYER_3_UP     58
#define LAMP_HEAD_PLAYER_4_UP     59
#define LAMP_HEAD_TILT            60
#define LAMP_HEAD_GAME_OVER       61
#define LAMP_HEAD_SHOOT_AGAIN     62
#define LAMP_HEAD_HIGH_SCORE      63


#define SW_PLUMB_TILT               0
#define SW_ROLL_TILT                1
#define SW_CREDIT_RESET             2
#define SW_COIN_1                   3
#define SW_COIN_2                   4
#define SW_COIN_3                   5
#define SW_SLAM_TILT                6
#define SW_HIGH_SCORE_RESET         7
#define SW_OUTHOLE                  8
#define SW_LEFT_OUTLANE             9
#define SW_LEFT_INLANE              10
#define SW_LEFT_SLINGSHOT           11
#define SW_LEFT_SAUCER              12
#define SW_UPPER_MID_LEFT_10PT      13
#define SW_SPINNER                  14
#define SW_TOP_LEFT_10PT            15
#define SW_1_STANDUP                16
#define SW_2_STANDUP                17
#define SW_3_STANDUP                18
// 19 is not used
#define SW_4_STANDUP                20
#define SW_5_STANDUP                21
#define SW_6_STANDUP                22
// 23 is not used
#define SW_BOTTOM_LEFT_POP          24
#define SW_TOP_LEFT_POP             25
#define SW_TOP_RIGHT_POP            26
#define SW_BOTTOM_RIGHT_POP         27
#define SW_TOP_CENTER_BULLSEYE      28
#define SW_RIGHT_SAUCER             29
#define SW_UPPER_TOP_RIGHT_10PT     30
#define SW_TOP_F                    31
#define SW_TOP_I                    32
#define SW_TOP_R                    33
#define SW_TOP_E                    34
#define SW_TOP_SAUCER               35
#define SW_LOWER_TOP_RIGHT_10PT     36
#define SW_MIDDLE_RIGHT_10PT        37
#define SW_POWER_1                  38
#define SW_POWER_2                  39
#define SW_POWER_3                  40
#define SW_RIGHT_SLINGSHOT          41
#define SW_RIGHT_OUTLANE            42
#define SW_RIGHT_INLANE             43
#define SW_RIGHT_FLIPPER            44
#define SW_SHOOTER_LANE             45
#define SW_PLAYFIELD_TILT           46
#define SW_LOWER_RIGHT_10PT         47
#define SW_CENTER_MIDDLE_LEFT_10PT  48
#define SW_LOWER_MIDDLE_LEFT_10PT   49
#define SW_TROUGH_3                 50
// 51 is not used
#define SW_LEFT_SAUCER_ROLLOVER     52
#define SW_RIGHT_SAUCER_ROLLOVER    53
// 54 is not used
// 55 is not used
#define SW_TROUGH_1                 56
#define SW_TROUGH_2                 57


#define SOL_KNOCKER                 13
#define SOL_OUTHOLE                 0
#define SOL_DROP_LEFT               1
#define SOL_DROP_RIGHT              2
#define SOL_SERVE_BALL              7
#define SOL_LEFT_SAUCER             3
#define SOL_RIGHT_SAUCER            4
#define SOL_TOP_SAUCER              5
#define SOL_BALLSAVE_KICKER         6
#define SOLCONT_COIN_LOCKOUT        15
